#!/bin/sh

# This is for the 'update-rc.d', so it knows when to start your service.
### BEGIN INIT INFO
# Provides:          your-script
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: a short description
# Description:       a long description
### END INIT INFO
start_server(){
    echo "Starting"
    /home/pawwik/dev/iot_server/SmartHomeServer
}
stop_server()
{
    echo "Stopping"
    killall SmartHomeServer
}
main () {
    case "$1" in
        stop)
            stop_server
            ;;
        start)
	    start_server
            ;;
        restart)
            echo "Restarting"
            stop_server
	    start_server
            ;;
        *)
        # wrong command
            echo "Unknown command: '$1'"
            ;;
    esac
}

main "$1" 2>&1 


# Better exit with success, not sure if this can screw up Ubuntus boot process.
exit 0
